Add edr client
openprocurement/openprocurement.integrations.edr pull request #4
Opened 2017-02-27 09:42 UTC by Krokop

Додав client.py який буде надсилати запити до ЕДР API.

Залежить від https://github.com/openprocurement/openprocurement.integrations.edr/pull/3

2017-03-03 16:25 UTC, kroman0 requested changes
requests.Session доцільніше для запитів на один host

2017-03-03 16:25 UTC, kroman0 commented on openprocurement/integrations/edr/client.py
> +        response = requests.get(url=url, headers=self.headers, timeout=self.timeout)
Тут доцільніше використати requests.Session

2017-03-06 08:51 UTC, Krokop commented on openprocurement/integrations/edr/client.py
> +        response = requests.get(url=url, headers=self.headers, timeout=self.timeout)
Додали session

2017-03-06 09:47 UTC, kroman0 approved these changes

2017-03-06 09:47 UTC, merged