One request
openprocurement/openprocurement.integrations.edr pull request #41
Opened 2017-07-07 07:21 UTC by gorserg

Зміни для реалізації одного запиту від Боту до Проксі.
Важливо прийняти зміни одночасно зі змінами до Боту (PR )

2017-07-07 11:39 UTC, itvan commented
@kroman0 please, review

2017-07-07 14:53 UTC, kroman0 commented
Необхідні зміни в документацію. Чи оновлення документації буде і іншому PR?

2017-07-07 15:01 UTC, kroman0 requested changes
Для зворотньої сумісності не бажано міняти основні помилки.

2017-07-07 15:01 UTC, kroman0 commented on openprocurement/integrations/edr/tests/verify.py
> +                         [{u'message': u'Wrong name of the GET parameter'}])
Це потребує оновлення документації.

2017-07-07 15:01 UTC, kroman0 commented on openprocurement/integrations/edr/tests/verify.py
> +        self.assertEqual(response.json['errors'][0]['description'], [{u'message': u'Content-Type of EDR API response is not application/json'}])
`Content-Type of EDR API response is not application/json` не проблема користувача. Для вирішення він не може нічого зробити.  `Forbidden` більш прийнятніша відповідь.

2017-07-07 15:03 UTC, kroman0 commented
Чи розглядалась можливість реалізації #9 перед впровадженням #10 ?

2017-07-10 06:35 UTC, itvan commented
Переносити на прод планували  #9 та #10 разом. На пісочницю - спочатку перехід на 1 запит, потім все інше.

2017-07-12 14:03 UTC, kroman0 requested changes

2017-07-12 14:03 UTC, kroman0 commented on openprocurement/integrations/edr/views/verify.py
> +            data.append({'data': prepare_data_details(response.json()),
Така зміна передбачає зміну загального формату відповіді verify запиту з dict на list. Доцільніше list зробити в data блоці.

2017-07-12 15:02 UTC, gorserg commented on openprocurement/integrations/edr/views/verify.py
> +            data.append({'data': prepare_data_details(response.json()),
Зараз формат відповіді на детальний запит буде виду (у випадку коли для коду ЄДРПОУ передбачено 2 елементи)
```
[
  {
    "meta": {
        "sourceDate": "2017-07-12T17:33:18.533325+03:00"
    }, 
    "data": { ... }
  },
  {
    "meta": {
        "sourceDate": "2017-07-12T17:33:19.533325+03:00"
    }, 
    "data": { ... }
  }
]
```
у атрибуті sourceDate дата з header відповіді від ЕДР, так як два запити виконувалить по черзі
Якщо переформатувати відповідь у структурі 
```
{
    "meta": {
        "sourceDate": "2017-07-12T17:33:18.533325+03:00"
    }, 
    "data": [{ ... }, { ... }]
}
```
То не зрозуміло яку дату з двох запитів брати до sourceDate.
Якщо стоїть задача уніфікаціх формату відповіді на простий і деталізований запит, то, мабуть, варто зробити окремі endpoint-и, наприклад 
`/api/1.0/verify?id=xxx` - для простого (роль platform)
`/api/1.0/verify_detail?id=xxx` - для детального (роль robot)

2017-07-13 09:02 UTC, kroman0 commented on openprocurement/integrations/edr/views/verify.py
> +            data.append({'data': prepare_data_details(response.json()),
Для того щоб не міняти формат відповіді доцільніше додати в блок meta sourceDate для детальних запитів. 
```
{
    "meta": {
        "sourceDate": "2017-07-12T17:33:18.533325+03:00",
        "detailsSourceDate": {} чи [{}, {}]
    }, 
    "data": [{ ... }, { ... }]
}
```
Назва поля detailsSourceDate і формат(чи list чи dict) на ваш розгляд. Формат поля в залежності від зручності прив'язки до конкретних даних в data. Якщо зручно зв'язати по позиції в data то можна list. Для жорсткішої зв'язки можна використати dict з ключем який ідентифікує конкретний блок в data.

2017-07-14 11:52 UTC, kroman0 requested changes
Остання поправка

2017-07-14 11:52 UTC, kroman0 commented on openprocurement/integrations/edr/tests/verify.py
> +import yaml
Цей yaml ніде не використовується.

2017-07-14 12:27 UTC, kroman0 approved these changes

2017-07-14 12:27 UTC, merged