Proxy
openprocurement/openprocurement.integrations.edr pull request #6
Opened 2017-03-06 10:16 UTC by Krokop

Додав view, tests, та конфігурації для запуску як окремого standalone.

2017-03-06 15:22 UTC, kroman0 requested changes

2017-03-06 15:22 UTC, kroman0 commented on openprocurement/integrations/edr/traversal.py
> +def factory(request):
Для proxy не потрібно factory оскільки в аплікації не передбачено контекст.

2017-03-06 15:22 UTC, kroman0 commented on openprocurement/integrations/edr/__init__.py
> +        authentication_policy=AuthenticationPolicy(settings['auth.file'], __name__),
Для proxy потрібно Basic Authentication з використанням імені і пароля користувача - https://github.com/openprocurement/openprocurement.documentservice/blob/master/openprocurement/documentservice/views.py#L29

2017-03-06 15:22 UTC, kroman0 commented on openprocurement/integrations/edr/traversal.py
> +def factory(request):
https://github.com/openprocurement/openprocurement.documentservice/blob/master/openprocurement/documentservice/views.py#L29

2017-03-06 15:22 UTC, kroman0 commented on openprocurement/integrations/edr/traversal.py
> +    __acl__ = [
потрібен поділ повноважень для майданчиків і бота(моста)

2017-03-06 17:07 UTC, Krokop commented on openprocurement/integrations/edr/traversal.py
> +    __acl__ = [
розділив

2017-03-06 17:07 UTC, Krokop commented on openprocurement/integrations/edr/traversal.py
> +def factory(request):
прибрав factory

2017-03-06 17:07 UTC, Krokop commented on openprocurement/integrations/edr/__init__.py
> +        authentication_policy=AuthenticationPolicy(settings['auth.file'], __name__),
переніс Authentication з document service.

2017-03-06 17:09 UTC, Krokop commented
Прибрав префікс, додав сканування всіх юзерів. Потрібен ревью

2017-03-07 09:51 UTC, kroman0 requested changes
Почистіть код від зайвого

2017-03-07 09:51 UTC, kroman0 commented on openprocurement/integrations/edr/__init__.py
> +SECURITY = {u'admins': {u'names': [], u'roles': ['_admin']}, u'members': {u'names': [], u'roles': ['_admin']}}
Його тут не треба

2017-03-07 09:51 UTC, kroman0 commented on openprocurement/integrations/edr/auth.py
> +class AuthenticationPolicy(BasicAuthAuthenticationPolicy):
AuthenticationPolicy вже не використовуєть

2017-03-07 09:51 UTC, kroman0 commented on openprocurement/integrations/edr/__init__.py
> +    config.registry.server_id = settings.get('id', '')
server_id, health_threshold і update_after не використовуються

2017-03-07 09:51 UTC, kroman0 commented on openprocurement/integrations/edr/utils.py
> +def beforerender(event):
цей beforerender потрібен тільки для op.api

2017-03-07 09:51 UTC, kroman0 commented on openprocurement/integrations/edr/utils.py
> +        (Allow, 'g:robots', 'verify'),
Роботу має надаватись розширений витяг з реєстру, тому доцільно додати g:robots додаткові повноваження, які будуть перевірятись в verify_user.

2017-03-07 10:17 UTC, Krokop commented on openprocurement/integrations/edr/__init__.py
> +SECURITY = {u'admins': {u'names': [], u'roles': ['_admin']}, u'members': {u'names': [], u'roles': ['_admin']}}
прибрав

2017-03-07 10:17 UTC, Krokop commented on openprocurement/integrations/edr/__init__.py
> +    config.registry.server_id = settings.get('id', '')
прибрав

2017-03-07 10:17 UTC, Krokop commented on openprocurement/integrations/edr/auth.py
> +class AuthenticationPolicy(BasicAuthAuthenticationPolicy):
прибрав

2017-03-07 10:17 UTC, Krokop commented on openprocurement/integrations/edr/utils.py
> +        (Allow, 'g:robots', 'verify'),
додав додав додаткові повноваження

2017-03-07 10:17 UTC, Krokop commented on openprocurement/integrations/edr/utils.py
> +def beforerender(event):
прибрав

2017-03-07 10:17 UTC, Krokop commented
Потрібен ревью

2017-03-07 10:57 UTC, kroman0 requested changes
Є части на коду, яка не використовується або не тестується, тести можна виключити з coverage - 
https://coveralls.io/github/openprocurement/openprocurement.integrations.edr. Потрібно прибрати все що потребує контексту чи згадки про тендери

2017-03-07 13:40 UTC, kroman0 requested changes
Ще трошки для coverage

2017-03-07 13:40 UTC, kroman0 commented on openprocurement/integrations/edr/auth.py
> +def get_local_roles(context):
і це також не потрібне

2017-03-07 13:40 UTC, kroman0 commented on openprocurement/integrations/edr/auth.py
> +def check_accreditation(request, level):
і це

2017-03-07 13:43 UTC, Krokop commented on openprocurement/integrations/edr/auth.py
> +def check_accreditation(request, level):
прибрав check_accreditation, бо він не використовувався

2017-03-07 13:59 UTC, Krokop commented on openprocurement/integrations/edr/auth.py
> +def get_local_roles(context):
get_local_roles потрібно видалити або покрити тестами?

2017-03-07 14:36 UTC, kroman0 commented on openprocurement/integrations/edr/auth.py
> +def get_local_roles(context):
get_local_roles не потрібне оскільки нема контексту для пошуку локальних ролей

2017-03-07 14:41 UTC, kroman0 commented
Не покритий тестами https://coveralls.io/builds/10470939/source?filename=openprocurement%2Fintegrations%2Fedr%2Fclient.py#L31 Чи буде це метод використовуватись?

2017-03-07 14:45 UTC, Krokop commented on openprocurement/integrations/edr/auth.py
> +def get_local_roles(context):
прибрав

2017-03-07 14:47 UTC, Krokop commented
https://coveralls.io/builds/10470939/source?filename=openprocurement%2Fintegrations%2Fedr%2Fclient.py#L31  - метод потрібен для наступного запиту на EDR, в наступному ПР будуть тести.

2017-03-07 15:10 UTC, kroman0 requested changes
Ще останні поправки і переходимо до наступних PR

2017-03-07 15:10 UTC, kroman0 commented on openprocurement/integrations/edr/utils.py
> +    if errors.request.matchdict:
route не має змінних параметрів, тому request.matchdict можна також забрати

2017-03-07 15:10 UTC, kroman0 commented on openprocurement/integrations/edr/utils.py
> +    if request.matchdict:
і тут

2017-03-07 15:10 UTC, kroman0 commented on openprocurement/integrations/edr/utils.py
> +        request.override_renderer = 'prettyjsonp'
Ще би мінімальний тест тут - https://coveralls.io/builds/10471928/source?filename=openprocurement%2Fintegrations%2Fedr%2Futils.py#L152
Подібно як тут - https://github.com/openprocurement/openprocurement.api/blob/master/src/openprocurement/api/tests/tender.py#L65

2017-03-07 15:30 UTC, Krokop commented on openprocurement/integrations/edr/utils.py
> +        request.override_renderer = 'prettyjsonp'
Додав

2017-03-07 15:30 UTC, Krokop commented on openprocurement/integrations/edr/utils.py
> +    if request.matchdict:
прибрав

2017-03-07 15:30 UTC, Krokop commented on openprocurement/integrations/edr/utils.py
> +    if errors.request.matchdict:
прибрав

2017-03-07 15:31 UTC, Krokop commented
Потрібен ревью

2017-03-07 16:07 UTC, kroman0 approved these changes

2017-03-07 16:09 UTC, kroman0 commented
Залишилось https://coveralls.io/builds/10472746/source?filename=openprocurement%2Fintegrations%2Fedr%2Futils.py#L152 але загалом 91% coverage.

2017-03-07 16:09 UTC, merged