Додав запит для отримання детальної інформації
openprocurement/openprocurement.integrations.edr pull request #7
Opened 2017-03-09 13:32 UTC by Krokop

2017-03-09 14:44 UTC, kroman0 requested changes

2017-03-09 14:44 UTC, kroman0 commented on openprocurement/integrations/edr/views/verify.py
> +def user_details(request):
1) розширена інформація має надаватись при запиті на verify за відповідних повноважень
2) get_subject може відповісти не одним записом?

2017-03-09 14:54 UTC, Krokop commented on openprocurement/integrations/edr/views/verify.py
> +def user_details(request):
1. Роботу потрібно мати доступ як до першого запиту так і для другого.
2. Так, іноді там може буди більше 1 елементу.

2017-03-09 15:32 UTC, kroman0 commented on openprocurement/integrations/edr/views/verify.py
> +def user_details(request):
1. Роботу у відповідь на перший запит повинна приходити розширена відповідь
2. Тобто під одним записом в ЄДР може бути кілка компаній?

2017-03-09 15:38 UTC, Krokop commented on openprocurement/integrations/edr/views/verify.py
> +def user_details(request):
1. Потрібно буде робити 2 запиті в проксі. На мою думку це час на обробку запиту виросте в двічі.
2. Це не можливо, але за документацією ЄДР може.

2017-03-10 15:07 UTC, kroman0 commented on openprocurement/integrations/edr/views/verify.py
> +def user_details(request):
1. Отже будемо робити 2 запити. Тут допоможе кешування відповідей на деякий час. Якщо пройде тільки перший запит і а другий ні, бот повторить запит і проксі виконає тільки запит за розширеною інформацією.
2. Ок, тоді масив відповідей підходить.

2017-03-10 15:23 UTC, Krokop commented on openprocurement/integrations/edr/views/verify.py
> +def user_details(request):
Це остаточна вимога? Ми маємо аргументи проти, зараз міст робить перший запит, результат складує в черзі, потім другий. Якщо, другий провалиться ми будемо повторювати тільки його. І не потрібно робити кеш на стороні проксі.

2017-03-10 16:50 UTC, kroman0 commented on openprocurement/integrations/edr/views/verify.py
> +def user_details(request):
Кеш однозначно потрібен. Проксі не може просто повторювати запит в ЄДР. Він мусить справляться в великим потоком запитів чи за штатних умов(в час пік) чи при нештатних (зацикленнях запитів від майданчиків чи моста). Також в час відновлення роботи моста після падіння велика частина запитів може відпрацьовувати з кеша.

2017-03-15 11:41 UTC, Krokop commented on openprocurement/integrations/edr/views/verify.py
> +def user_details(request):
Отримали підтвердження від ДП Прозорро, що кеш вирішено перенести на другий етап реалізації.

2017-03-15 15:49 UTC, kroman0 commented on openprocurement/integrations/edr/views/verify.py
> +def user_details(request):
Ок. Тоді потрібно виконати п. 1 https://github.com/openprocurement/openprocurement.integrations.edr/pull/7#discussion_r105414590 тільки "Отже будемо робити 2 запити."

2017-03-16 06:59 UTC, itvan commented on openprocurement/integrations/edr/views/verify.py
> +def user_details(request):
Також ДП підтвердило поточну реалізацію взаємодії Проксі-Бот(2 запити від Бота)
Якщо зауважень більше немає, прошу виконати merge та викласти Проксі на пісочницю.

2017-03-17 12:26 UTC, merged